config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :employees
  
  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  root 'kudos#index'

  namespace :admins do
    resources :kudos, only: %i[index destroy]
    root 'pages#dashboard'
    resources :employees do
      patch 'add_available_kudos', on: :collection
    end
    resources :company_values
    resources :rewards do
      collection do
        get 'import'
        post 'import'
      end
    end
    resources :orders, only: :index do
      patch 'deliver', on: :member
      patch 'prepare_to_pick_up', on: :member
    end
    resources :categories
    resources :online_codes, only: %i[index new create destroy] do
      collection do
        post 'import'
      end
    end
  end
end

app/models/company_value.rb
class CompanyValue < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  has_many :kudos, dependent: :destroy
end

app/controllers/admins/company_values_controller.rb
module Admins
  class CompanyValuesController < AdminsController
    def index
      @company_values = CompanyValue.all
    end

    def show
      @company_value = CompanyValue.find(params[:id])
    end

    def edit
      @company_value = CompanyValue.find(params[:id])
    end

    def new
      @company_value = CompanyValue.new
    end

    def create
      @company_value = CompanyValue.new(company_value_params)
      @company_value.save!
      redirect_to admins_company_values_path, notice: 'Company Value was successfully created.'
    rescue ActiveRecord::RecordInvalid => e
      render :new, notice: e.message
    end

    def destroy
      @company_value = CompanyValue.find(params[:id])
      @company_value.destroy
      redirect_to admins_company_values_url, notice: 'Company Value was successfully destroyed.'
    end

    def update
      @company_value = CompanyValue.find(params[:id])
      @company_value.update(company_value_params)
      @company_value.save!
      redirect_to admins_company_values_path, notice: 'Company Value was successfully updated.'
    rescue ActiveRecord::RecordInvalid => e
      render :edit, notice: e.message
    end

    private

    def company_value_params
      params.require(:company_value).permit(:title)
    end
  end
end

app/views/admins/company_values/_form.html.erb
<%= form_with(model: [:admins, @company_value]) do |form| %>
  <% if company_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_value.errors.count, "error") %> prohibited this company value from being saved:</h2>

      <ul>
        <% company_value.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/admins/company_values/edit.html.erb
<h1>Editing Company Value</h1>

<%= render 'form', company_value: @company_value %>

<%= link_to 'Show', admins_company_value_path(@company_value) %> |
<%= link_to 'Back', admins_company_values_path %>

app/views/admins/company_values/index.html.erb
<h1>Company Values</h1>
  <table class='table'>
    <thead class="table-dark">
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @company_values.each do |company_value| %>
        <tr>
          <td><%= company_value.title %></td>
          <td><%= link_to 'Show', admins_company_value_path(company_value) %></td>
          <td><%= link_to 'Edit', edit_admins_company_value_path(company_value) %></td>
          <td><%= link_to 'Destroy', admins_company_value_path(company_value), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<br>
<%= link_to 'New Company Value', new_admins_company_value_path %>

app/views/admins/company_values/new.html.erb
<h1>New Company Value</h1>

<%= render 'form', company_value: @company_value %>

<%= link_to 'Back', admins_company_values_path %>

app/views/admins/company_values/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @company_value.title %>
</p>

<%= link_to 'Edit', edit_admins_company_value_path(@company_value) %> |
<%= link_to 'Back', admins_company_values_path %>