config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :employees
  
  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  root 'kudos#index'

  namespace :admins do
    resources :kudos, only: %i[index destroy]
    root 'pages#dashboard'
    resources :employees do
      patch 'add_available_kudos', on: :collection
    end
    resources :company_values
    resources :rewards do
      collection do
        get 'import'
        post 'import'
      end
    end
    resources :orders, only: :index do
      patch 'deliver', on: :member
      patch 'prepare_to_pick_up', on: :member
    end
    resources :categories
    resources :online_codes, only: %i[index new create destroy] do
      collection do
        post 'import'
      end
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :given_kudos, class_name: 'Kudo', foreign_key: 'giver_id', dependent: :destroy, inverse_of: :giver
  has_many :received_kudos, class_name: 'Kudo', foreign_key: 'receiver_id', dependent: :destroy, inverse_of: :receiver
  has_many :orders, dependent: :destroy
  has_one :address, dependent: :destroy
  has_many :online_codes, dependent: :destroy

  validates :first_name, :last_name, presence: true

  def full_name
    [first_name, last_name].join(' ')
  end
end

app/controllers/admins/employees_controller.rb
module Admins
  class EmployeesController < AdminsController
    def index
      @employees = Employee.all
    end

    def show
      @employee = Employee.find(params[:id])
      @orders = @employee.orders.includes([:reward]).order(delivery_status: :desc)
    end

    def edit
      @employee = Employee.find(params[:id])
    end

    def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy
      redirect_to admins_employees_url, notice: 'Employee was successfully destroyed.'
    end

    def update
      @employee = Employee.find(params[:id])

      if params[:employee][:password].blank?
        @employee.update(employee_params_without_password)
      else
        @employee.update(employee_params)
      end
      @employee.save!
      redirect_to admins_employees_url(@employee), notice: 'Employee was successfully updated.'
    rescue ActiveRecord::RecordInvalid => e
      render :edit, notice: e.message
    end

    def add_available_kudos
      unless params[:number_of_additional_kudos].to_i.between? 1, 20
        redirect_to admins_employees_path, notice: 'Additional kudos must be between 1 and 20' and return
      end

      begin
        ActiveRecord::Base.transaction do
          Employee.all.each do |employee|
            employee.update!(number_of_available_kudos: employee.number_of_available_kudos + params[:number_of_additional_kudos].to_i)
          end
        end
        redirect_to admins_employees_path, notice: 'Additional kudos added'
      rescue ActiveRecord::RecordInvalid
        redirect_to admins_employees_path, notice: 'Error: Additional kudos not added'
      end
    end

    private

    def employee_params
      params.require(:employee).permit(:email, :password, :number_of_available_kudos, :first_name, :last_name)
    end

    def employee_params_without_password
      params.require(:employee).permit(:email, :number_of_available_kudos, :first_name, :last_name)
    end
  end
end

app/views/admins/employees/_form.html.erb
<%= form_with(model: [:admins, @employee]) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %><br />
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %><br />
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %><br />
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %><br />
    <%= form.text_field :password %>
  </div>

    <div class="field">
    <%= form.label :number_of_available_kudos %><br />
    <%= form.number_field :number_of_available_kudos %>
  </div><br />

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', admins_employee_path(@employee) %> |
<%= link_to 'Back', admins_employees_path %>

app/views/admins/employees/index.html.erb
<h1>Add Available Kudos</h1>

<%= form_with url: add_available_kudos_admins_employees_path(@employees), method: :patch do |form| %>
  <%= form.number_field :number_of_additional_kudos, in: 1..20, step: 1 %>
  <%= form.submit "Add kudos" %>
<% end %>

<h1>Employees</h1>

  <table class="table">
    <thead class="table-dark">
      <tr>
        <th>Full name</th>
        <th>Email</th>
        <th>Number of kudos</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @employees.each do |employee| %>
        <tr employee-id="<%= employee.id %>">
          <td><%= employee.full_name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.number_of_available_kudos %></td>
          <td><%= link_to 'Show', admins_employee_path(employee) %></td>
          <td><%= link_to 'Edit', edit_admins_employee_path(employee) %></td>
          <td><%= link_to 'Destroy', admins_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<br>

app/views/admins/employees/show.html.erb
<p>
  <h1>Employee information</h1>
  <strong>Full name:</strong>
    <%= @employee.full_name %></br>
  <strong>Email:</strong>
    <%= @employee.email %></br>
  <strong>Points:</strong>
    <%= @employee.number_of_available_points %></br>
  <strong>Available kudos:</strong>
    <%= @employee.number_of_available_kudos %>
</p>
<%= link_to 'Edit', edit_admins_employee_path(@employee) %> |
<%= link_to 'Back', admins_employees_path %>
<p>
  <h1>Employee orders</h1>
      <%= render 'admins/pages/orders', orders: @orders %>
</p>