config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :employees
  
  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  root 'kudos#index'

  namespace :admins do
    resources :kudos, only: %i[index destroy]
    root 'pages#dashboard'
    resources :employees do
      patch 'add_available_kudos', on: :collection
    end
    resources :company_values
    resources :rewards do
      collection do
        get 'import'
        post 'import'
      end
    end
    resources :orders, only: :index do
      patch 'deliver', on: :member
      patch 'prepare_to_pick_up', on: :member
    end
    resources :categories
    resources :online_codes, only: %i[index new create destroy] do
      collection do
        post 'import'
      end
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :rewards, dependent: :destroy

  validates :title, presence: true
end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < AdminsController
    def index
      @categories = Category.all
    end

    def edit
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      @category.save!
      redirect_to admins_categories_path, notice: 'Category was successfully created.'
    rescue ActiveRecord::RecordInvalid => e
      render :new, notice: e.message
    end

    def destroy
      @category = Category.find(params[:id])
      if @category.rewards.none?
        @category.destroy
        redirect_to admins_categories_url, notice: 'Category was successfully destroyed.'
      else
        redirect_to admins_categories_url, notice: "This category has rewards. You can't destroy it"
      end
    end

    def update
      @category = Category.find(params[:id])
      @category.update(category_params)
      @category.save!
      redirect_to admins_categories_path, notice: 'Category was successfully updated.'
    rescue ActiveRecord::RecordInvalid => e
      render :edit, notice: e.message
    end

    private

    def category_params
      params.require(:category).permit(:title)
    end
  end
end

app/views/admins/categories/_form.html.erb
<%= form_with(model: [:admins, @category]) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/admins/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admins_categories_path %>

app/views/admins/categories/index.html.erb
<h1>Categories</h1>
  <table class='table'>
    <thead class="table-dark">
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.title %></td>
          <td><%= link_to 'Edit', edit_admins_category_path(category) %></td>
          <td><%= link_to 'Destroy', admins_category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<br>
<%= link_to 'New Category', new_admins_category_path %>

app/views/admins/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', admins_categories_path %>