config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  devise_for :employees
  
  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  root 'kudos#index'

  namespace :admins do
    resources :kudos, only: %i[index destroy]
    root 'pages#dashboard'
    resources :employees do
      patch 'add_available_kudos', on: :collection
    end
    resources :company_values
    resources :rewards do
      collection do
        get 'import'
        post 'import'
      end
    end
    resources :orders, only: :index do
      patch 'deliver', on: :member
      patch 'prepare_to_pick_up', on: :member
    end
    resources :categories
    resources :online_codes, only: %i[index new create destroy] do
      collection do
        post 'import'
      end
    end
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :title, :description, :price, presence: true
  validates :title, uniqueness: true
  validates :reward_photo, blob: { content_type: ['image/png', 'image/jpg'] }
  validates :number_of_available_items, presence: true, if: :post?
  validates :number_of_available_items, numericality: { greater_than_or_equal_to: 0 }, if: :online?

  has_many :orders, dependent: :destroy
  has_many :online_codes, dependent: :destroy
  belongs_to :category, optional: true
  has_one_attached :reward_photo

  paginates_per 3

  enum delivery_method: { online: 'online', post: 'post', pick_up: 'pick-up' }

  scope :available, -> { where('number_of_available_items > 0') }
end

app/controllers/admins/rewards_controller.rb
module Admins
  class RewardsController < AdminsController
    def index
      @rewards = Reward.all.includes(:category)
    end

    def show
      @reward = Reward.find(params[:id])
    end

    def edit
      @reward = Reward.find(params[:id])
    end

    def new
      @reward = Reward.new
    end

    def create
      @reward = Reward.new(reward_params)
      @reward.save!
      redirect_to admins_rewards_path, notice: 'Reward was successfully created.'
    rescue ActiveRecord::RecordInvalid => e
      render :new, notice: e.message
    end

    def destroy
      @reward = Reward.find(params[:id])
      @reward.destroy
      redirect_to admins_rewards_url, notice: 'Reward was successfully destroyed.'
    end

    def update
      @reward = Reward.find(params[:id])
      @reward.update(reward_params)
      @reward.save!
      redirect_to admins_rewards_path, notice: 'Reward was successfully updated.'
    rescue ActiveRecord::RecordInvalid => e
      render :edit, notice: e.message
    end

    def import
      if request.request_method == 'GET'
        render :import_form
      else
        file = params[:file]
        import_service = ImportRewardsService.new(file)
        return redirect_to import_admins_rewards_path, notice: import_service.errors.join(', ') unless import_service.call

        redirect_to admins_rewards_path, notice: 'Rewards imported!'
      end
    end

    private

    def reward_params
      params.require(:reward).permit(:title, :description, :price, :category_id, :reward_photo, :delivery_method, :number_of_available_items)
    end
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :authenticate_employee!

  def index
    @categories = Category.all
    @rewards = RewardsQuery.new(filters: index_query_params).call.page params[:page]
  end

  def show
    @reward = Reward.find(params[:id])
  end
end

private

def index_query_params
  params.permit(:category)
end

app/views/admins/rewards/_form.html.erb
<%= form_with(model: [:admins, @reward]) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %><br />
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %><br />
    <%= form.collection_select :category_id, Category.all, :id, :title, include_blank: "None" %>
  </div>

  <div class="field">
    <%= form.label :delivery_method %><br />
    <%= form.select :delivery_method, Reward.delivery_methods.values %>
  </div>

  <div class="field">
    <%= form.label :number_of_available_items, "Number of available items (for post items)" %><br />
    <%= form.number_field :number_of_available_items, step: :any %>
  </div>

  <div class="field">
    <%= form.label :price %><br />
    <%= form.number_field :price, step: :any %>
  </div>

  <div class="field"><br />
    <%= form.label :reward_photo %>
    <%= form.file_field :reward_photo %>
  </div> 

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Show', admins_reward_path(@reward) %> |
<%= link_to 'Back', admins_rewards_path %>

app/views/admins/rewards/import.html.erb
  <%= form_with url: import_create_admins_rewards_path, method: :post do |form| %>
    <%= form.file_field :file, accept: ".csv" %>
    <%= form.button "Import" %>
  <% end %>

app/views/admins/rewards/import_form.html.erb
  <%= form_with url: import_admins_rewards_path, method: :post do |form| %>
    <%= form.file_field :file, accept: ".csv" %>
    <%= form.button "Import" %>
  <% end %>

app/views/admins/rewards/index.html.erb
<h1>Rewards</h1>
  <table class="table">
    <thead class="table-dark">
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Category</th>
        <th>Number of available items</th>
        <th>Delivery method</th>

        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @rewards.each do |reward| %>
        <tr>
          <td><%= reward.title %></td>
          <td><%= reward.description %></td>
          <td><%= number_to_currency(reward.price) %></td>
          <% if reward.category.present? %>
            <td><%= reward.category.title %></td>
          <% else %>
            <td>(no category)</td>
          <% end %>
          <td><%= reward.number_of_available_items %></td>
          <td><%= reward.delivery_method.humanize %></td>
          <td><%= link_to 'Show', admins_reward_path(reward) %></td>
          <td><%= link_to 'Edit', edit_admins_reward_path(reward) %></td>
          <td><%= link_to 'Destroy', admins_reward_path(reward), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
</table>
<br>
<%= link_to 'New Reward', new_admins_reward_path %>
<%= link_to 'Import Rewards', import_admins_rewards_path %>

app/views/admins/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form', reward: @reward %>

<%= link_to 'Back', admins_rewards_path %>

app/views/admins/rewards/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @reward.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @reward.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @reward.price %>
</p>
<p>
  <strong>Delivery method:</strong>
  <%= Reward.delivery_methods[@reward.delivery_method] %>
</p>
<p>
  <% if @reward.reward_photo.present? %>
      <strong>Photo:</strong></br>
      <%= image_tag @reward.reward_photo %>
  <% end %>
</p>

<%= link_to 'Edit', edit_admins_reward_path(@reward) %> |
<%= link_to 'Back', admins_rewards_path %>